services:
  reverse-proxy:
    image: lucaslorentz/caddy-docker-proxy:2.8.10
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - server-data:/data
      - server-config:/config
    extra_hosts:
      - host.docker.internal:host-gateway

networks:
  default:
    name: none
    external: true

volumes:
  server-data:
  server-config:
