services:
  reverse-proxy:
    ports:
      - 80:80
    networks:
      - proxied
    environment:
      - CADDY_INGRESS_NETWORKS=caddy-ingress
    labels:
      caddy.auto_https: disable_redirects

networks:
  proxied:
    name: caddy-ingress
