services:
  hello:
    image: nginxdemos/hello:0.3
    networks:
      - caddy-ingress
    labels:
      caddy: :80
      caddy.redir: /hello /hello/
      caddy.handle_path: /hello/*
      caddy.handle_path.reverse_proxy: "{{upstreams 80}}"

networks:
  caddy-ingress:
    external: true
