services:
  whoami:
    image: traefik/whoami:v1.10.1
    networks:
      - caddy-ingress
    labels:
      caddy: :80
      caddy.redir: /whoami /whoami/
      caddy.handle_path: /whoami/*
      caddy.handle_path.reverse_proxy: "{{upstreams 80}}"

networks:
  caddy-ingress:
    external: true
